### ISSUE TITLE
好玩系列：拥有它，XML文件少一半--更方便的处理View背景

### ISSUE THREAD

**Issue by leobert-lan** [leobert-lan/Blog#4]
使用DaVinCi 处理背景

**Comment by hongyangAndroid** [comment]
hi，我是鸿洋，看你的系列文章写的很赞，可以授权公众号转载吗，会标识作者，原文链接？另外我的微信是 zhy3867，欢迎保持沟通。

**Comment by leobert-lan** [comment]
@hongyangAndroid 感觉鸿洋老哥提供的公众号平台推广机会，文章可授权转载。具体情况我们可以微信详聊，有些文章我在郭霖老哥那边投了，避免重复了影响号主文章因子。
